### ISSUE TITLE
Specifing *.kicad_pro file as parameter seems not to work

### ISSUE THREAD

**Issue by Nerade** [leoheck/kiri#106]
Hello,

I am currently trying to get kiri work for our purposes. Unfortunately I have encountered a potential issue. The project I am trying to use has more than one `*.kicad_pro` file present. I'm aware of the fact that this should be prevented but some workflows cause this situation of having multiple `*.kicad_pro` files in one folder (like panelization). As far as I can tell (I am not very proficient with bash) there are at least two methods to determine the project file. The positional parameter is checked and parsed but later in the actual business logic it is derived by running `find` on the project folder with the file extension filter.

I have now moved the additional project file in a sub-solder but this will break as soon as I hit the git revision with the file still in project root. Is there an easy fix so that the script will always use the file name specified as optional argument?

Thanks in advance

**Comment by Nerade** [comment]
Thank you for your fast response! :)

We are trying to integrate KiRI as part of our Gitlab CI/CD as follows:

```
default:
  image: leoheck/kiri:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
  
build-job:
  stage: build
  script:
    - pwd
    - git config --global --add safe.directory $(pwd)
    - ls -lah
    - git status
    - echo "export TERM=xterm" >> ~/.zshrc
    - zsh -c -i "kiri -l -t 10 -k -d plot_output -dp -dk -D -x my_pcb_project.kicad_pro"
  artifacts:
    when: on_success
    name: "plot-result"
    paths:
      - plot_output/
      - "*.tgz"
```
